/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MappaRouteImport } from './routes/mappa'
import { Route as GalleriaRouteImport } from './routes/galleria'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampioniIdRouteImport } from './routes/campioni.$id'

const MappaRoute = MappaRouteImport.update({
  id: '/mappa',
  path: '/mappa',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriaRoute = GalleriaRouteImport.update({
  id: '/galleria',
  path: '/galleria',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampioniIdRoute = CampioniIdRouteImport.update({
  id: '/campioni/$id',
  path: '/campioni/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/galleria': typeof GalleriaRoute
  '/mappa': typeof MappaRoute
  '/campioni/$id': typeof CampioniIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/galleria': typeof GalleriaRoute
  '/mappa': typeof MappaRoute
  '/campioni/$id': typeof CampioniIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/galleria': typeof GalleriaRoute
  '/mappa': typeof MappaRoute
  '/campioni/$id': typeof CampioniIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/galleria' | '/mappa' | '/campioni/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/galleria' | '/mappa' | '/campioni/$id'
  id: '__root__' | '/' | '/about' | '/galleria' | '/mappa' | '/campioni/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleriaRoute: typeof GalleriaRoute
  MappaRoute: typeof MappaRoute
  CampioniIdRoute: typeof CampioniIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mappa': {
      id: '/mappa'
      path: '/mappa'
      fullPath: '/mappa'
      preLoaderRoute: typeof MappaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleria': {
      id: '/galleria'
      path: '/galleria'
      fullPath: '/galleria'
      preLoaderRoute: typeof GalleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campioni/$id': {
      id: '/campioni/$id'
      path: '/campioni/$id'
      fullPath: '/campioni/$id'
      preLoaderRoute: typeof CampioniIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleriaRoute: GalleriaRoute,
  MappaRoute: MappaRoute,
  CampioniIdRoute: CampioniIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
